# chat/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/', views.profile_settings, name='profile_settings'),
    path('inbox/', views.inbox, name='inbox'),
    path('inbox/summary/', views.inbox_summary, name='inbox_summary'),
    path('friends/', views.friends_view, name='friends'),
    path('friends/add/', views.add_friend_page, name='add_friend'),
    path('moments/', views.moments_view, name='moments'),
    path('rooms/create/', views.create_room_page, name='create_room'),
    path('rooms/discover/', views.discover_rooms_page, name='discover_rooms'),
    path('rooms/join/<str:room_id>/', views.join_room, name='join_room'),
    path('rooms/invite/', views.invite_to_room, name='invite_to_room'),
    path('rooms/invitations/<int:invitation_id>/respond/', views.respond_room_invitation, name='respond_room_invitation'),
    path('rooms/requests/<int:request_id>/respond/', views.respond_room_join_request, name='respond_room_join_request'),
    path('users/<str:username>/', views.user_profile, name='user_profile'),
    path('dm/<str:username>/', views.direct_chat, name='direct_chat'),
    path('dm/<str:username>/delete/', views.delete_direct_conversation, name='delete_direct_conversation'),
    path('friends/remove/<str:username>/', views.remove_friend, name='remove_friend'),
    path('friends/request/', views.send_friend_request, name='send_friend_request'),
    path('friends/respond/<int:request_id>/', views.respond_friend_request, name='respond_friend_request'),
    path('location/update/', views.update_precise_location, name='update_precise_location'),
    path('read/room/<str:room_name>/', views.mark_room_read, name='mark_room_read'),
    path('read/dm/<str:username>/', views.mark_direct_read, name='mark_direct_read'),
    path('delete/<str:room_name>/', views.delete_room, name='delete_room'),
    path('admin/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/settings/', views.admin_site_settings, name='admin_site_settings'),
    path('admin/users/', views.admin_users, name='admin_users'),
    path('admin/users/<int:user_id>/password/', views.admin_user_password, name='admin_user_password'),
    path('admin/rooms/', views.admin_rooms, name='admin_rooms'),
    path('admin/sessions/', views.admin_sessions, name='admin_sessions'),
    path('', views.index, name='chat_index'),
    path('<str:room_name>/', views.room, name='chat_room'),
]
