# Generated by Django 5.2.11 on 2026-03-20 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_userlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='匿名用户', max_length=100, verbose_name='用户名')),
                ('message', models.TextField(verbose_name='消息内容')),
                ('message_type', models.CharField(default='chat', max_length=20, verbose_name='消息类型')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room', verbose_name='房间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['room', '-timestamp'], name='chat_messag_room_id_a3de54_idx')],
            },
        ),
    ]
