# Generated by Django 5.2.11 on 2026-03-21 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_room_avatar_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='location_label',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='位置摘要'),
        ),
        migrations.CreateModel(
            name='UserChatProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_theme', models.CharField(default='amber', max_length=20, verbose_name='聊天配色')),
                ('bubble_style', models.CharField(default='soft', max_length=20, verbose_name='气泡样式')),
                ('show_location', models.BooleanField(default=True, verbose_name='显示大致位置')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '聊天外观',
                'verbose_name_plural': '聊天外观',
            },
        ),
    ]
