# Generated by Django 5.2.11 on 2026-03-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_location_label_userchatprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='district',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='区/县'),
        ),
    ]
