# Generated by Django 5.2.11 on 2026-03-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_userlocation_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatprofile',
            name='avatar_label',
            field=models.CharField(blank=True, default='', max_length=24, verbose_name='头像文本'),
        ),
    ]
