# Generated by Django 5.2.11 on 2026-03-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_userchatprofile_avatar_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='township',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='镇/街道'),
        ),
    ]
