# Generated by Django 5.2.11 on 2026-03-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_userchatprofile_friend_id_friendrequest_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchatprofile',
            name='friend_id',
            field=models.CharField(blank=True, default=None, max_length=24, null=True, unique=True, verbose_name='好友ID'),
        ),
    ]
