# Generated by Django 5.2.11 on 2026-03-21 16:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_alter_userchatprofile_friend_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=160, verbose_name='个人介绍'),
        ),
        migrations.AlterField(
            model_name='userchatprofile',
            name='friend_id',
            field=models.CharField(blank=True, default=None, max_length=11, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(8), django.core.validators.RegexValidator(message='好友 ID 只能包含小写字母、数字或下划线', regex='^[a-z0-9_]+$')], verbose_name='好友ID'),
        ),
        migrations.CreateModel(
            name='DirectConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_conversations_started', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_conversations_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '私聊会话',
                'verbose_name_plural': '私聊会话',
            },
        ),
        migrations.CreateModel(
            name='DirectConversationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='chat.directconversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_conversation_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '私聊状态',
                'verbose_name_plural': '私聊状态',
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.directconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '私聊消息',
                'verbose_name_plural': '私聊消息',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='directconversation',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_direct_conversation_pair'),
        ),
        migrations.AddConstraint(
            model_name='directconversationstate',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_direct_conversation_state'),
        ),
    ]
