# Generated by Codex on 2026-03-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_userchatprofile_bio_alter_userchatprofile_friend_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='directconversationstate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directconversationstate',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RoomVisitState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_states', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_visit_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '群聊访问状态',
                'verbose_name_plural': '群聊访问状态',
            },
        ),
        migrations.AddConstraint(
            model_name='roomvisitstate',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_room_visit_state'),
        ),
    ]
