# Generated by Codex on 2026-03-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_room_memberships(apps, schema_editor):
    Room = apps.get_model('chat', 'Room')
    Message = apps.get_model('chat', 'Message')
    RoomMembership = apps.get_model('chat', 'RoomMembership')
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])

    for room in Room.objects.all():
        user_ids = set()
        if room.created_by_id:
            user_ids.add(room.created_by_id)

        message_user_ids = Message.objects.filter(room=room, user__isnull=False).values_list('user_id', flat=True)
        user_ids.update(message_user_ids)

        usernames = set(
            Message.objects.filter(room=room, user__isnull=True).exclude(username='').values_list('username', flat=True)
        )
        if usernames:
            matched_user_ids = User.objects.filter(username__in=usernames).values_list('id', flat=True)
            user_ids.update(matched_user_ids)

        for user_id in user_ids:
            RoomMembership.objects.get_or_create(
                room_id=room.id,
                user_id=user_id,
                defaults={
                    'is_active': True,
                    'removed_at': None,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_directconversationstate_last_read_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否仍在群中')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='加入时间')),
                ('removed_at', models.DateTimeField(blank=True, null=True, verbose_name='移出时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '群成员',
                'verbose_name_plural': '群成员',
            },
        ),
        migrations.AddConstraint(
            model_name='roommembership',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='unique_room_membership'),
        ),
        migrations.RunPython(backfill_room_memberships, migrations.RunPython.noop),
    ]
