# Generated by Codex on 2026-03-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_roommembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trusted_origins', models.TextField(blank=True, default='', verbose_name='CSRF 受信任来源')),
                ('cors_allowed_origins', models.TextField(blank=True, default='', verbose_name='CORS 允许来源')),
                ('allow_all_cors', models.BooleanField(default=False, verbose_name='允许全部跨域来源')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
    ]
