# Generated by Django 5.2.11 on 2026-03-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_roomvisitstate_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/direct/%Y/%m/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='attachment_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='附件 MIME'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='附件文件名'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0, verbose_name='附件大小'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='attachment_type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件')], default='text', max_length=20, verbose_name='附件类型'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/rooms/%Y/%m/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_mime',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='附件 MIME'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='附件文件名'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_size',
            field=models.PositiveIntegerField(default=0, verbose_name='附件大小'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件')], default='text', max_length=20, verbose_name='附件类型'),
        ),
        migrations.AlterField(
            model_name='directmessage',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='消息内容'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(blank=True, default='', verbose_name='消息内容'),
        ),
    ]
