# Generated by Django 5.2.11 on 2026-03-23 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_directmessage_attachment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=60, verbose_name='表情名称')),
                ('image', models.ImageField(upload_to='emoji_items/%Y/%m/', verbose_name='表情图片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emoji_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '图片表情',
                'verbose_name_plural': '图片表情',
                'ordering': ['-created_at'],
            },
        ),
    ]
