# Generated by Django 5.2.11 on 2026-03-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_useremoji'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremoji',
            options={'ordering': ['-last_used_at', '-created_at'], 'verbose_name': '图片表情', 'verbose_name_plural': '图片表情'},
        ),
        migrations.AddField(
            model_name='useremoji',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最近使用时间'),
        ),
    ]
