# Generated by Django 5.2.11 on 2026-03-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_userchatprofile_public_id_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='chat_attachment_max_mb',
            field=models.PositiveIntegerField(default=50, verbose_name='聊天附件大小上限(MB)'),
        ),
    ]
